source: app
destination: app/_site

# Site settings
title: edomus.io
description: > # this means to ignore newlines until "baseurl:"
  edomus.io

author: edomus.io
author_website: https://edomus.io/
email: andrew.bernstein00@gmail.com

#baseurl: "/edomus"  # Subpath of your site, e.g. /blog. For deploying to github pages, this should match your repo name
                            # Currently `gulp serve:dist` does not work with a baseurl specified. For this purpose,
                            # temporarily comment out this parameter
url: "http://littlerkap.github.io"  # Base hostname & protocol for your site

#twitter_username: edomus
#github_username:  edomus
#disqus_shortname: juliaebert
#google_analytics: UA-54476418-1

# Pagination
paginate: 4
paginate_path: "/blog/page:num"
excerpt_separator: <!--more-->

# Gems
gems:
  - jekyll-archives
  - jekyll-paginate

# Build settings
markdown: kramdown
permalink: pretty

# Archive settings
jekyll-archives:
  enabled: ['tags']
